
nombre = input("Nombres y apellidos: ")
print(" ")                                                
print("Responde correctamente las siguientes preguntas, marcando la alternativa correcta: ")
print(" ")
print("Pregunta 1.- En que año se independizó el Perú :")
print(" ")
print("a) 1834")
print("b) 1820")
print("c) 1900")
print("d) 1821")
print(" ")
Clave_1 = input("respuesta: ")
if Clave_1 == "d":
  print("La respuesta es correcta.")
else:
  print("La respuesta es incorrecta")
print(" ")
print(" ")
espera_1 = input("Presiona enter para la siguiente pregunta")
print(" ")
print(" ")
print("Pregunta 2.- Quien es el autor de la siguiente frase, Pienso, luego existo?: ")
print(" ")
print("a) Descartes")
print("b) platon")
print("c) Marx")
print("d) Aristoteles")
print(" ")
Clave_2 = input("respuesta: ")
if Clave_2 == "a":
  print("La respuesta es correcta.")
else:
  print("La respuesta es incorrecta")
print(" ")
print(" ")
espera_2 = input("Presiona enter para la siguiente pregunta")
print(" ")
print(" ")
print("Pregunta 3.- ¿Cual es el libro mas vendido en el mundo despues de la biblia?: ")
print(" ")
print("a) El Señor de los Anillos")
print("b) Don Quijote de la Mancha")
print("c) El Principito")
print("d) Cien años de Soledad")
print(" ")
Clave_3 = input("respuesta: ")
if Clave_3 == "b":
  print("La respuesta es correcta.")
else:
  print("La respuesta es incorrecta")
print(" ")
print(" ")
print("Gracias por participar!!")